services:

  neko:
    image: m1k1o/neko:chromium   # firefox
    restart: unless-stopped
    shm_size: 2gb
    ports:
      - "8380:8080"
      - "52000-52100:52000-52100/udp"
    cap_add:
      - SYS_ADMIN
    environment:
      - NEKO_SCREEN=1920x1080@30
      - NEKO_PASSWORD=neko
      - NEKO_PASSWORD_ADMIN=admin
      - NEKO_EPR=52000-52100
      - NEKO_NAT1TO1=<tu-IP>
